version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: api-db1
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    depends_on:
      - db
    external_links:
      - api-db1:api-db1